name: Build Vectordb Docker Image for linux/amd64 and linux/arm64

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build:
  
    name: Build All-in-One Vectordb Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get Current Date 
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
          
    - name: Build
      env:
        DOCKER_HUB_REPOSITORY: epsilla/vectordb
        SHA_TAG: ${{ github.sha }}
      run: |
        export IMAGE_TAG=${{ steps.date.outputs.date }}
        export IMAGE_TAG_LATEST="latest"
        echo "IMAGE_TAG: ${IMAGE_TAG}";
        echo "SHA: ${SHA_TAG}";

        pwd;ls -la;
        cd engine;
        pwd;ls -la;
        docker build --pull --build-arg="RELEASE_VERSION=${IMAGE_TAG}" \   
                            -t ${DOCKER_HUB_REPOSITORY}:${IMAGE_TAG}-amd64 .;
        docker push ${DOCKER_HUB_REPOSITORY}:${IMAGE_TAG}-amd64

        

        
        


        
